### ISSUE TITLE
Disclaimer controls not operable by mouse in Relativity 10+

### ISSUE THREAD

**Issue by KaNaPaPi** [relativitydev/disclaimer-acceptance-log#2]
Unable to click disclaimer checkbox via mouse click, submit button via mouse click, also will not save user acceptance in database after submitting.

It is possible to check the checkbox by tabbing into control and hitting spacebar.
It is possible to click submit button by tabbing into control and hitting enter key.

**Comment by mrobustelli** [comment]
Closing this issue because the fix for Issue #1 solves this problem.
